pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 1, unit: 'HOURS')
    }

    triggers { githubPush() }

    environment {
        PYTHON_VERSION = '3.8'
        GIT_CREDENTIALS = credentials('RonGitUser')
        REPO_URL = 'https://github.com/ron1120/basic-cloud-deployment.git'
        DISCORD_TOKEN = credentials('DISCORD_TOKEN')

    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    git branch: 'main', credentialsId: env.GIT_CREDENTIALS, url: env.REPO_URL

                    env.GIT_BRANCH_NAME = sh(script: 'git rev-parse --abbrev-ref HEAD', returnStdout: true).trim()

                    if (env.GIT_BRANCH_NAME == 'main') {
                        echo "On main branch, proceeding with build and deploy."
                    } else {
                        error "Not on main branch, aborting pipeline."
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'cd discord-bot && python3 -m venv venv'
                sh 'cd discord-bot && ./venv/bin/pip install -r requirements.txt'
                sh 'cd discord-bot && nohup ./venv/bin/python bot.py &'
                sh 'echo "Deployment complete."'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
