pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 1, unit: 'HOURS')
    }

    triggers { githubPush() }

    environment {
        PYTHON_VERSION = '3.8'
        GIT_CREDENTIALS = credentials('RonGitUser')
        REPO_URL = 'https://github.com/ron1120/basic-cloud-deployment.git'
        DISCORD_TOKEN = credentials('DISCORD_TOKEN')

    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    git branch: 'main', credentialsId: env.GIT_CREDENTIALS, url: env.REPO_URL

                    env.GIT_BRANCH_NAME = sh(script: 'git rev-parse --abbrev-ref HEAD', returnStdout: true).trim()

                    if (env.GIT_BRANCH_NAME == 'main') {
                        echo "On main branch, proceeding with build and deploy."
                    } else {
                        error "Not on main branch, aborting pipeline."
                    }
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
                sh 'docker stop discord-bot || true'
                sh 'docker rm discord-bot || true'
                sh 'docker build -t discord-bot ./discord-bot'
                sh "docker run -d --name discord-bot -e DISCORD_TOKEN=${DISCORD_TOKEN} discord-bot"
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
        always {
            sh 'docker stop discord-bot || true'
            sh 'docker rm discord-bot || true'
            sh 'docker image prune -f || true'
            cleanWs()
        }
    }
}
